### ISSUE TITLE
CD to pypi.org

### ISSUE THREAD

**Issue by phainom** [INWTlab/dbrequests#17]
We should implement a publish command for publishing to [pypi.org](https://pypi.org/project/dbrequests/), as well as adding CD on the master branch within travis. Not sure how travis handles secrets, I'll have to look into this.

**Comment by wahani** [comment]
I will also check, if GitHub actions are prepared for this. I assume they are.

**Comment by wahani** [comment]
I set up a github action to do this. We need an access token for pypi and test-pypi and then we will publish:

- to test pypi on every commit on master
- and to pypi with every tagged commit on master

I followed the instructions on https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github -- there is also a description how to setup an access token. @phainom I guess the package is bound to your account? We would need `test_pypi_password` and `pypi_password` and add them to the secrets section of this repository.

**Comment by phainom** [comment]
I added the access token and it pushes to test Pypi, but somehow the tagged commit https://github.com/INWTlab/dbrequests/releases/tag/v1.3.2-deploy does not trigger the Github action for "normal" Pypi, I dont know why - does it need certain tags?

**Comment by wahani** [comment]
@phainom I will look into it. Hope I get this to work soon.

**Comment by wahani** [comment]
One of those rare occasions where I can fix something at 11:30pm that I couldn't fix at 11:30am. Anyways, it works now. 

- Note that the deployment to test-pypi will fail if the version number has already been deployed. 
- A release to pypi is triggered by a [release here on GitHub](https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository) or by a tag, which is automatically turned into a release by GitHub. This Build-Job is then bound to the Tag, not the Commit, unfortunately. You can see the successful deployment of v1.3.8 at https://github.com/INWTlab/dbrequests/runs/546694507?check_suite_focus=true. Not sure how to make that more transparent. Mybe two jobs for this task, so we can use the batch in the Readme properly.

**Caveat**

- Currently we can publish to Pypi even if the tests fail. Although it is unlikely that one of us is tagging a commit while tests are failing, I still need to fix that.

**Comment by phainom** [comment]
It seems you still need to change time to summer time. :p Thanks for figuring it out, I was pretty annoyed trying random pushes yesterday.

So what exactly did you run to make it work? I tried yesterday to git push tags, which didnt work. 

Cant Github actions run the tests? I guess it would make sense to consolidate testing and deployment either in Travis or github actions.

**Comment by wahani** [comment]
> Cant Github actions run the tests? I guess it would make sense to consolidate testing and deployment either in Travis or github actions.

Absolutely, they can. We just have to take the time to set everything up. I will try and do that when I find the time. Actions seem to be the way to go, quite a good piece of infrastructure.

> So what exactly did you run to make it work? I tried yesterday to git push tags, which didnt work.

First, the config I was linking to doesn't work just like that. The thing is, that when we push to the master, the `github.ref` is always `refs/head`, doesn't matter if we add a tag or not. That's why in the original config the job always skipped the deployment to Pypi. When we add a tag, aka prepare a release, this is an own event and can trigger a dedicated job. So I had to add the `release` trigger  to the configuration. That job is then not bound to a commit, but to the release. You can see that in the build history, where the release is not on master, not really anyway:

![grafik](https://user-images.githubusercontent.com/3105646/77992356-339b7900-7326-11ea-9d68-55372552577c.png)

All very exciting. At least now it seems to work.

**Comment by wahani** [comment]
Seems to work now. Just released 1.3.9 to PyPI with no issues.
